import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import Navbar from "./_components/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body >
        <Navbar />
        <div className={styles.body}>{children}</div>
      </body>
    </html>
  );
}
